# Generated by Django 5.1.5 on 2025-02-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('id_iqama_no', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('details', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
