# Generated by Django 5.1.5 on 2025-02-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_remove_certificate_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
