# Generated by Django 5.1.5 on 2025-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_alter_certificate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='company',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='s_office',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='ts_no',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
