# Generated by Django 5.1.3 on 2025-02-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_certificate_company_certificate_s_office_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='valid_until',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='details',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='id_iqama_no',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='s_office',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='ts_no',
        ),
        migrations.AddField(
            model_name='certificate',
            name='card_no',
            field=models.CharField(default=11, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='iqama_number',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='operator_name',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='operator_trade',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='operator_profiles/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='undercard',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='company',
            field=models.CharField(max_length=150),
        ),
    ]
