# Generated by Django 5.1.3 on 2025-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_rename_valid_until_certificate_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
