# Generated by Django 5.1.3 on 2025-02-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0007_certificate_certificate_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='undercard',
            field=models.CharField(default=11, max_length=150),
            preserve_default=False,
        ),
    ]
